name: Build and publish

on: [push, pull_request]

jobs:

  build_wheels_on_ubuntu:
    name: Build wheels on ubuntu-20.04
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.4.0
        
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_wheels_on_windows:
    name: Build wheels on windows-2019
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.4.0
        
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_wheels_on_macos:
    name: Build wheels on macos-10.15
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install Clang with openmp
        run: brew install llvm libomp

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.4.0

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm
        submodules: true  # Optional, use if you have submodules

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*.tar.gz
  
  publish_on_pypi:
    name: Publish on PyPI
    needs:
      - build_wheels_on_ubuntu
      - build_wheels_on_windows
      - build_wheels_on_macos
      - build_sdist
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}