name: Publish on PyPI

on: [push]

jobs:
  publish_on_pypi:
    needs: 
      - build_wheels_on_ubuntu
      - build_wheels_on_windows
      - build_wheels_on_macos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: Publish package to TestPyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/