name: Publish on PyPI

on:
  workflow_run:
    workflows: ["Build Wheels"]
    branches: [main]
    types: [completed]

jobs:
  publish_on_pypi:
    name: Publish on PyPI
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Build Wheels
          path: dist

      - name: Publish package to TestPyPI
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/